name: Build and Deploy

on:
  push:
    branches:
      - main  # Ana dalı değiştirdiğiniz varsayıldı, gerekirse ayarlayın.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7

    - name: Install Dependencies
      run: |
        gem install bundler
        bundle install

    - name: Build
      run: |
        bundle exec jekyll build  # Burada jekyll build komutunu değiştirin

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: ./
